### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by vincedani** [szeged/Freya#17]
#### Issue description

I would like to build the Freya as it is written in the [`README.md`](https://github.com/szeged/Freya/blob/master/README.md), but I get configuration error in the second step: `./configure --prefix=`pwd`/inst`

#### Steps to reproduce the issue

1. Clone the repository
2. Follow the build steps

#### What's the expected result?

- Configuration is successful. 

#### What's the actual result?

```
checking for a supported version of gcc... no (7)
configure: error: please use gcc >= 3.0 or clang >= 2.9 or icc >= 13.0
```

GCC version: `gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0`

**Comment by dati91** [comment]
Did you tried this?
http://valgrind.10908.n7.nabble.com/Compiling-valgrind-with-non-default-gcc-td42871.html

**Comment by vincedani** [comment]
I have removed the line `as_fn_error $? "please use gcc >= 3.0 or clang >= 2.9 or icc >= 13.0" "$LINENO" 5` from the generated `configure` script and now it works.

Thanks @dati91
